image:
  file: .gitpod.Dockerfile

ports:
- port: 8080
  onOpen: open-preview

tasks:
- before: >
    source ~/.bashrc
  init: >
    cd LabelStoreMax &&
    flutter clean &&
    flutter channel stable &&
    flutter upgrade &&
    flutter doctor -v &&
    flutter pub get &&
    flutter run -d web-server --no-resident # prebuilds the app
  command: >
    flutter run -d web-server --web-port=8080 --web-hostname=0.0.0.0
